#!/bin/bash

# Function to stage changes, commit with the generated message, and push
push_changes() {
  local commit_message="$1"
  git add .
  git commit -m "$commit_message"
  git push
}

# Check if at least 1 arguments are provided
if [ "$#" -lt 1 ]; then
  echo "Error: There is no arguments."
  exit 1
fi

# Check if at least 2 arguments are provided
if [ "$#" -lt 2 ]; then
  commit_message="${*:1}"
  push_changes "$commit_message"
  exit 0
fi

# Assign arguments to variables
action=$1
task_num=$2
task_name=$3
error=$4

# Determine the commit message based on the action
if [ "$action" == "edit" ]; then
   # If an additional argument is provided, include it in the message
   if [ -n "$error" ]; then
     commit_message="Task${task_num}[Edit]: ${task_name} {${error}}"
   else
     echo "Error: Edit action requires an additional argument."
     exit 1
   fi
elif [ "$action" == "add" ]; then
   if [ -n "$task_name" ]; then
     commit_message="Task${task_num}[Add]: ${task_name}"
   else
     echo "Error: Edit action requires an additional argument."
     exit 1
   fi
else
   echo "Error: Action must be 'edit' or 'add'."
   exit 1
fi
# Call the function to push changes
push_changes "$commit_message"

